# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        default_adapter:
            local:
                directory: '%kernel.cache_dir%/flysystem'
        s3_adapter:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: 'bailleau'

    filesystems:
        default_filesystem:
            adapter: default_adapter
            alias: League\Flysystem\Filesystem

        s3_filesystem:
            adapter: s3_adapter
            visibility: public
