twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'include/form/bootstrap_5_layout.html.twig'
    date:
        timezone: Europe/Paris
    globals:
        menuService: '@App\Service\MenuService'